spring:
  application:
    name: ms-human
  datasource:
    url: jdbc:postgresql://localhost:5432/SpringTest
    password: root
    username: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 4444